# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaverMapA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'NMapsMap'
  # Pods for NaverMapA

  target 'NaverMapATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaverMapAUITests' do
    # Pods for testing
  end

end
